# Generated by Django 5.2.3 on 2025-06-26 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
